from django.db import models

# Create your models here.


class RawUFCData(models.Model):
    date = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    weight_class = models.CharField(max_length=100)
    title_bout = models.BooleanField()
    winner = models.CharField(max_length=100)
    red_Fighter = models.CharField(max_length=100)
    blue_Fighter = models.CharField(max_length=100)
    red_KD = models.IntegerField()
    blue_KD = models.IntegerField()
    red_Sig_str = models.IntegerField()
    blue_Sig_str = models.IntegerField()
    red_Sig_str_percent = models.FloatField()
    blue_Sig_str_percent = models.FloatField()
    red_Total_str = models.IntegerField()
    blue_Total_str = models.IntegerField()
    red_Td = models.IntegerField()
    blue_Td = models.IntegerField()
    red_Td_percent = models.FloatField()
    blue_Td_percent = models.FloatField()
    red_Sub_att = models.IntegerField()
    blue_Sub_att = models.IntegerField()
    red_Rev = models.IntegerField()
    blue_Rev = models.IntegerField()
    red_Ctrl = models.IntegerField()
    blue_Ctrl = models.IntegerField()
    red_Height = models.FloatField()
    red_Weight = models.FloatField()
    red_Reach = models.FloatField()
    red_STANCE = models.CharField(max_length=100, default="Orthodox", blank=True)
    red_DOB = models.CharField(max_length=100)
    red_SLpM = models.FloatField()
    red_Str_Acc = models.FloatField()
    red_SApM = models.FloatField()
    red_Str_Def = models.FloatField()
    red_TD_Avg = models.FloatField()
    red_TD_Acc = models.FloatField()
    red_TD_Def = models.FloatField()
    red_Sub_Avg = models.FloatField()
    red_record = models.CharField(max_length=100)
    blue_Height = models.FloatField()
    blue_Weight = models.FloatField()
    blue_Reach = models.FloatField()
    blue_STANCE = models.CharField(max_length=100, default="Orthodox", blank=True)
    blue_DOB = models.CharField(max_length=100)
    blue_SLpM = models.FloatField()
    blue_Str_Acc = models.FloatField()
    blue_SApM = models.FloatField()
    blue_Str_Def = models.FloatField()
    blue_TD_Avg = models.FloatField()
    blue_TD_Acc = models.FloatField()
    blue_TD_Def = models.FloatField()
    blue_Sub_Avg = models.FloatField()
    blue_record = models.CharField(max_length=100)
