# FILE NOT STRUCTURED PROPERLY YET

FROM python:3.12-slim-buster

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    VIRTUAL_ENV=/opt/venv

# Create and activate virtual environment
RUN python -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"

# Set work directory
WORKDIR /ufc_project

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    libpq-dev \
    curl \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Install uv
RUN curl -LsSf https://astral.sh/uv/install.sh | sh

# Install Python dependencies using uv
COPY requirements.txt .
RUN uv pip install --upgrade pip \
    && uv pip install -r requirements.txt

# Copy project
COPY . .

# Expose port for Django
EXPOSE 8000

# Run Django server
CMD ["uv", "run", "manage.py", "runserver", "0.0.0.0:8000"]
