# FILE NOT STRUCTURED PROPERLY YET

FROM python:3.10-slim-buster

COPY . /ufc_project/

RUN pip install --upgrade pip

RUN pip install -r /ufc_project/requirements.txt

RUN apt-get -y clean

WORKDIR /ufc_project

CMD ["python", "main.py"]