# FILE NOT STRUCTURED PROPERLY YET

FROM python:3.10-slim-buster

# COPY ./requirements.txt /ufc_scraper/requirements.txt
COPY . /ufc_scraper/

RUN pip install --upgrade pip

RUN pip install -r /ufc_scraper/requirements.txt

RUN apt-get -y clean


WORKDIR /ufc_scraper

# CMD ["python", "main.py"]